[pdf]
dpi = 150
encoding = "UTF-8"
header_left = "[title]"
header_right = "[page]/[toPage]"
header_spacing = 2
margin_top = "15mm"
margin_bottom = "18mm"
margin_left = "25mm"
margin_right = "18mm"
header_line = true
enable_local_file_access = true


