[basic]
input_file = "data/input/words_to_lookup.txt"
dictionary_file = "data/mdict/Learn These Words First/Learn These Words First.mdx"
output_file = "data/output/words_to_lookup.html"
with_toc = true
add_timestamp = true
backup_input = true
save_invalid_words = true

[css]
preset_label = ""
preset_text = ""

[image]
width = 0  # 0 means auto
zoom = 1.0
background = true

[image.jpg]
quality = 85

[image.png]
optimize = true
compress_level = 9
transparent_bg = false

[image.webp]
quality = 80
lossless = false
transparent_bg = false

[pdf]
preset_label = ""
preset_text = ""

[advanced]
wkhtmltopdf_path = "auto"