[input]
file = "data/input/words_to_lookup.txt"

[dictionary]
file = "data/mdict/Learn These Words First/Learn These Words First.mdx"

[output]
file = "data/output/words_to_lookup.html"
with_toc = true
add_timestamp = true
backup_input = true
save_invalid_words = true

[advanced]
wkhtmltopdf_path = "auto"